eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8050
spring:
  application:
    name: real-project
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
